### ISSUE TITLE
osdslet daemon failure

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/opensds-formula#20]
Running osdslet as daemon fails with error logged
```
[root@localhost opensds]# nohup /opt/opensds-linux-amd64/bin/osdslet >/var/log/opensds/osdslet.out 2> /var/log/opensds/osdslet.err &

[root@localhost opensds]# cat osdslet.localhost.root.log.ERROR.20181214-213525.2829 
Log file created at: 2018/12/14 21:35:25
Running on machine: localhost
Binary: Built with gc go1.10.4 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1214 21:35:25.442800    2829 keystone.go:60] When get auth client:You must provide a password to authenticate
```

**Comment by noelmcloughlin** [comment]
@leonwanghui 
Is `osdslet` the controller?  I'm getting above error - what am I missing?

**Comment by leonwanghui** [comment]
Yes

**Comment by leonwanghui** [comment]
I think you just enabled `keystone` authentication but didn't provide the valid username and password. For the first step, I suggest you configure `OpensdsAuthStragety=noauth`

**Comment by noelmcloughlin** [comment]
Like this?
```
[osdslet]
api_endpoint = 192.168.1.11:50040
graceful = True
socket_order = inc
log_file = /var/log/opensds/osdslet.log
##auth_strategy = keystone
auth_strategy=noauth
```

**Comment by leonwanghui** [comment]
Yes, you can replace that using some commands like ‘sed’
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/saltstack-formulas/opensds-formula","title":"saltstack-formulas/opensds-formula","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/saltstack-formulas/opensds-formula"}},"updates":{"snippets":[{"icon":"PERSON","message":"@noelmcloughlin in #20: Like this?\r\n```\r\n[osdslet]\r\napi_endpoint = 192.168.1.11:50040\r\ngraceful = True\r\nsocket_order = inc\r\nlog_file = /var/log/opensds/osdslet.log\r\n##auth_strategy = keystone\r\nauth_strategy=noauth\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/saltstack-formulas/opensds-formula/issues/20#issuecomment-448217797"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/saltstack-formulas/opensds-formula/issues/20#issuecomment-448217797",
"url": "https://github.com/saltstack-formulas/opensds-formula/issues/20#issuecomment-448217797",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by leonwanghui** [comment]
Can you share your updated config file? Have you restarted osdslet service after modifying the field? I think it still has some auth issues.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/saltstack-formulas/opensds-formula","title":"saltstack-formulas/opensds-formula","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/saltstack-formulas/opensds-formula"}},"updates":{"snippets":[{"icon":"PERSON","message":"@noelmcloughlin in #20: Thanks. I executed again with `noauth` set and service started.\r\n\r\nHave you seen this error before?\r\n```\r\nvagrant@ubuntu1804:~$ export OPENSDS_ENDPOINT=http://192.168.1.12:50040\r\nvagrant@ubuntu1804:~$ export OPENSDS_AUTH_STRATEGY=noauth  \r\nvagrant@ubuntu1804:~$ source /opt/opensds-linux-amd64-devstack/openrc admin admin\r\n\r\nWARNING: setting legacy OS_TENANT_NAME to support cli tools.\r\nvagrant@ubuntu1804:~$ \r\nvagrant@ubuntu1804:~$ osdsctl pool list \r\nERROR: List pools failed: context deadline exceeded\r\nvagrant@ubuntu1804:~$ osdsctl profile create '{\"name\": \"default\", \"description\": \"default policy\"}'\r\nERROR: Create profile failed: rpc error: code = Unavailable desc = transport is closing\r\nvagrant@ubuntu1804:~$ osdsctl volume create 1 --name=test-001\r\nERROR: Create volume failed: context deadline exceeded\r\nvagrant@ubuntu1804:~$ osdsctl volume list\r\n\r\nERROR: List volumes failed: context deadline exceeded\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/saltstack-formulas/opensds-formula/issues/20#issuecomment-448238929"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/saltstack-formulas/opensds-formula/issues/20#issuecomment-448238929",
"url": "https://github.com/saltstack-formulas/opensds-formula/issues/20#issuecomment-448238929",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by noelmcloughlin** [comment]
$ cat /etc/opensds/opensds.conf 
```
[keystone_authtoken]
auth_type = password
project_name = service
user_domain_name = Default
auth_url = http://192.168.1.12/identity
memcached_servers = 192.168.1.12:11211
project_domain_name = Default

[osdslet]
api_endpoint = 192.168.1.12:50040
graceful = True
socket_order = inc
log_file = /var/log/opensds/osdslet.log
auth_strategy = noauth

[osdsdock]
api_endpoint = 192.168.1.12:50050
dock_type = provisioner
log_file = /var/log/opensds/osdsdock.log
enabled_backends = lvm
enabled_backend = lvm
```
$ cat lvm.yaml 
```
"tgtBindIp": "192.168.1.12"
"tgtConfDir": "/etc/tgt/conf.d"
"pool":
  "opensds-volumes":
    "storageType": "block"
    "availabilityZone": "default"
    "extras":
      "dataStorage":
        "provisioningPolicy": "Thin"
        "isSpaceEfficient": "False"
      "advanced":
        "a": "b"
        "latency": "5ms"
        "diskType": "SSD"
      "ioConnectivity":
        "accessProtocol": "iscsi"
        "maxBWS": "600"
        "maxIOPS": "7000000"
```

**Comment by noelmcloughlin** [comment]
$ curl http://192.168.1.12/identity
{"versions": {"values": [{"status": "stable", "updated": "2018-10-15T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v3+json"}], "id": "v3.11", "links": [{"href": "http://192.168.1.12/identity/v3/", "rel": "self"}]}]}}

$ osdsctl volume list --debug
DEBUG: 2018/12/18 09:42:39 receiver.go:75: GET http://192.168.1.12:50040/v1beta/e93b4c0934da416eb9c8d120c5d04d96/block/volumes?offset=0&sortDir=desc&sortKey=id&limit=50
DEBUG: 2018/12/18 09:42:42 receiver.go:101: 
StatusCode: 400 Bad Request
Response Body:
{"code":400,"message":"List volumes failed: context deadline exceeded"}
ERROR: List volumes failed: context deadline exceeded

**Comment by noelmcloughlin** [comment]
Note: I updated `opensds-installer/salt` PR with [fixes](https://github.com/saltstack-formulas/opensds-formula/pull/21) ...
- Ensure memcached is listing on HOST_IP
- Ensure username, password, default_domain_name exist in `opensds.conf`.

Just to recap the `osdslet` daemon is now running.  The current issue is getting the CLI working.
```
[keystone_authtoken]
auth_type = password
username = opensdsv0.3.3
project_name = service
user_domain_name = Default
project_default_name = Default
auth_url = http://192.168.1.13/identity
memcached_servers = 192.168.1.13:11211
password = opensds@123
project_domain_name = Default

[osdslet]
api_endpoint = 192.168.1.13:50040
graceful = True
socket_order = inc
log_file = /var/log/opensds/osdslet.log
auth_strategy = noauth

[osdsdock]
api_endpoint = 192.168.1.13:50050
dock_type = provisioner
log_file = /var/log/opensds/osdsdock.log
enabled_backends = lvm
enabled_backend = lvm
```
CLI issue
```
vagrant@ubuntu1804:~$ osdsctl pool list --debug
DEBUG: 2018/12/18 14:54:07 receiver.go:75: GET http://192.168.1.13:50040/v1beta/e93b4c0934da416eb9c8d120c5d04d96/pools?offset=0&sortDir=desc&limit=50&sortKey=id
DEBUG: 2018/12/18 14:54:10 receiver.go:101: 
StatusCode: 400 Bad Request
Response Body:
{"code":400,"message":"List pools failed: context deadline exceeded"}
ERROR: List pools failed: context deadline exceeded

vagrant@ubuntu1804:~$ ps -ef | grep osds
root     10685 10621 94 14:14 ?        00:37:12 /usr/bin/osdsdock
root     20394     1 99 12:31 pts/0    03:20:51 /opt/opensds-linux-amd64/bin/osdslet

vagrant@ubuntu1804:~$ netstat -tuplan | grep 50040
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 192.168.1.13:50040      0.0.0.0:*               LISTEN      -                   
tcp        0      0 192.168.1.13:38012      192.168.1.13:50040      TIME_WAIT   -                   
tcp        0      0 192.168.1.13:55708      192.168.1.13:50040      TIME_WAIT   - 
```

**Comment by leonwanghui** [comment]
That's weired, I can share the auth config info in ansible:
```conf
[keystone_authtoken]
memcached_servers = $HOST_IP:11211
signing_dir = /var/cache/opensds
cafile = /opt/stack/data/ca-bundle.pem
auth_uri = http://$HOST_IP/identity
project_domain_name = Default
project_name = service
user_domain_name = Default
password = $STACK_PASSWORD
username = $OPENSDS_SERVER_NAME
auth_url = http://$HOST_IP/identity
auth_type = password
```

And something I need to make sure is if you restarted `osdslet` daemon service after updating `opensds.conf`?

**Comment by noelmcloughlin** [comment]
Thanks. I'll do some more troubleshooting. Maybe username is wrong in my config. I have confirmed that firewall is not the issue anyway.

**Comment by noelmcloughlin** [comment]
My code is missing nginx reverse proxy - I have updated code to fix this and will test tomorrow.

I see this line in `ansible/scripts/keystone.sh` but cannot locate the json file on filesystem?
```
cp "$OPENSDS_DIR/examples/policy.json" "$OPENSDS_CONFIG_DIR"
```
Where or what is this file?

**Comment by leonwanghui** [comment]
It's located at [here](https://github.com/opensds/opensds/blob/master/examples/policy.json), you need to copy it into your project.

**Comment by noelmcloughlin** [comment]
Thanks - found it.
