### ISSUE TITLE
Salt 2019.2 support missing

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/opensds-formula#81]
Please use Salt 2018.3 or 2017.7 with this formula.  

Various states consumed by opensds-formula may be impacted by [NON-BACKWARD-COMPATIBLE CHANGE TO YAML RENDERER](https://docs.saltstack.com/en/develop/topics/releases/2019.2.0.html#non-backward-compatible-change-to-yaml-renderer)

**Comment by noelmcloughlin** [comment]
Works fine with `Salt 2018.3`

**Comment by myii** [comment]
@noelmcloughlin Maybe put this at the top of the `README`?  This is too easy to miss here under issues.

**Comment by noelmcloughlin** [comment]
Good idea @myii
